### ISSUE TITLE
Never enables VR mode

### ISSUE THREAD

**Issue by jobobby04** [Bluscream/UnityVRPatcher#3]
https://github.com/Bluscream/UnityVRPatcher/blob/f364d2afe49c02a718d820839bf0bd2175a5646d/UnityVRPatcher/Mod.cs#L83-L88

It never actually enables VR

**Comment by jobobby04** [comment]
Actually this is probably unrelated to my issue. It seems like later unity versions require more work then what it says in the guide. The XR settings isn't even included unless the developer installs a plugin https://forum.unity.com/threads/xr-settings-not-showing.948544/

**Comment by Bluscream** [comment]
Look at https://github.com/Raicuparta/uuvr if you want a more compatible universal vr mod
